# make use of vm's 
sudo: 'required'

# have the docker service set up (we'll
# update it later)
services:
  - 'docker'

language: python
python:
  - "2.7"

# prepare the machine before any code
# installation scripts
# before_install:
#   - './.travis/main.sh'

# first execute the test suite.
# after the test execution is done and didn't
# fail, build the images (if this step fails
# the whole Travis build is considered a failure).
script:
  - 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
  - 'python generate.py'

# don't notify me when things fail
notifications:
  email: false